apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: aizy4ynnb-dotnet-basic 
  janus-idp.io/tekton: aizy4ynnb-dotnet-basic
  backstage.io/kubernetes-id: aizy4ynnb-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: aizy4ynnb-dotnet-basic
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  